name: Convert Markdown to PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install pandoc
        run: sudo apt-get install -y texlive-full pandoc ruby rake

      - name: convert markdown to pdf
        run: pandoc README.md -o resume.pdf --pdf-engine=lualatex -V documentclass=ltjsarticle -V luatexjapresetoptions=morisawa

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-resume
          path: resume.pdf