name: Convert Markdown to PDF and release

on:
  pull_request:
    types: [closed]
    branches:
      - main
  push:
    paths:
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: git checkout
        uses: actions/checkout@v4

      # Doc: https://github.com/marketplace/actions/markdownlint-cli2-action
      - name: markdown linter
        uses: DavidAnson/markdownlint-cli2-action@v16.0.0
        with:
          fix: true
          config: 'config/.markdownlint.json'
          globs: |
            README.md

      - name: install pandoc
        run: sudo apt-get install -y texlive-full pandoc ruby rake
          
      - name: convert markdown to pdf
        run: pandoc README.md -o resume.pdf --pdf-engine=lualatex -V documentclass=ltjsarticle -V luatexjapresetoptions=morisawa

      - name: resume zip archive
        run: zip resume.zip resume.pdf

      - name: set current datetime as env variable-1
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d')" >> "$GITHUB_ENV"

      - name: set current datetime as env variable-2
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME2=$(date +'%Y/%m/%d')" >> "$GITHUB_ENV"

      - name: release
        uses: softprops/action-gh-release@v2
        with:
          name: "Release ${{ env.CURRENT_DATETIME }}"
          tag_name: "update_${{ env.CURRENT_DATETIME }}"
          body: "${{ env.CURRENT_DATETIME2 }} 時点の職務経歴書"
          draft: false
          prerelease: false
          make_latest: true
          files: |
            resume.pdf
