name: Convert Markdown to PDF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install pandoc
        run: sudo apt-get install -y texlive-full pandoc ruby rake

      - name: convert markdown to pdf
        run: > 
          pandoc README.md -o resume.pdf
            -V documentclass=ltjarticle
            -V geometry:a4paper
            -V geometry:margin=2.5cm
            -V geometry:nohead
            --pdf-engine=lualatex

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-resume
          path: resume.pdf